# Generated by Django 5.0.6 on 2026-08-08 14:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_login_throttle_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount (EGP)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Caps the discount for percentage coupons. Ignored for fixed-amount coupons.', max_digits=10, null=True)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('applies_to', models.CharField(choices=[('meals', 'Meals only'), ('subscriptions', 'Subscriptions only'), ('both', 'Meals & subscriptions')], default='both', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total redemptions allowed. Blank = unlimited.', null=True)),
                ('per_customer_limit', models.PositiveIntegerField(blank=True, help_text='Redemptions allowed per phone number. Blank = unlimited.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cutoff_hours_before', models.PositiveIntegerField(default=0, help_text='Hours before start_time after which this slot can no longer be booked. 0 = no cutoff.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, help_text='Static path (images/meals/chicken-rice.webp) or full https:// URL.', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EGP. Meals are Egypt-only in this phase.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('ingredients', models.TextField(blank=True)),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('maintain', 'Maintain Weight')], db_index=True, max_length=20)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], db_index=True, max_length=20)),
                ('daily_capacity', models.PositiveIntegerField(default=0, help_text='Maximum units of this meal that can be delivered on a single day. 0 means unlimited. See MealDailyAvailability for per-date overrides and live reservation counts.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealDailyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('capacity_override', models.PositiveIntegerField(blank=True, help_text="Overrides the meal's default daily capacity for this date only.", null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Mark this meal unavailable for this date regardless of capacity.')),
                ('reserved', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('plan_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('maintain', 'Maintain Weight')], max_length=20)),
                ('meals_per_day', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on delivery'), ('online', 'Online payment')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('fawaterk_invoice_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fawaterk_invoice_key', models.CharField(blank=True, max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('access_token', models.CharField(db_index=True, editable=False, max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('goal', models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('maintain', 'Maintain Weight')], max_length=20)),
                ('meals_per_day', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price in EGP for the whole plan duration (7 or 30 days).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['plan_type', 'goal', 'meals_per_day'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='meals.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.UniqueConstraint(fields=('weekday', 'start_time', 'end_time'), name='unique_delivery_slot_window'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['goal', 'meal_type', 'is_active'], name='meals_meal_goal_c2f7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['is_active', 'calories'], name='meals_meal_is_acti_44bc4a_idx'),
        ),
        migrations.AddField(
            model_name='mealdailyavailability',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_availability', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='meals.coupon'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='meals.deliveryslot'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='meals.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptiondelivery',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='subscription_deliveries', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='subscriptiondelivery',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='meals.subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplanprice',
            constraint=models.UniqueConstraint(fields=('plan_type', 'goal', 'meals_per_day'), name='unique_plan_price_combo'),
        ),
        migrations.AddIndex(
            model_name='mealdailyavailability',
            index=models.Index(fields=['meal', 'date'], name='meals_meald_meal_id_82c4ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealdailyavailability',
            constraint=models.UniqueConstraint(fields=('meal', 'date'), name='unique_meal_availability_per_date'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'start_date'], name='meals_subsc_status_4fea73_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiondelivery',
            constraint=models.UniqueConstraint(fields=('subscription', 'scheduled_date'), name='unique_subscription_delivery_per_date'),
        ),
    ]
