# Generated by Django 5.0.6 on 2026-08-10 08:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('store', '0009_order_coupon_order_delivery_date_order_delivery_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dietary_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='disliked_foods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='meals.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptiondelivery',
            name='auto_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide from the public average/listing without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='meals.meal')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='store.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meal', 'is_hidden'], name='meals_revie_meal_id_126603_idx')],
            },
        ),
    ]
