# Generated by Django 5.0.6 on 2026-08-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_number_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'permissions': [('access_dashboard', 'Can access the store dashboard')]},
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('EG', 'Egypt'), ('SA', 'Saudi Arabia')], default='EG', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='governorate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('path', models.CharField(max_length=255)),
                ('referrer_host', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=10)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='store_pagev_created_249e83_idx'), models.Index(fields=['session_key', 'path'], name='store_pagev_session_c0f3f6_idx')],
            },
        ),
    ]
